name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm test -- --coverage

      - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

      - name: Upload coverage to Codecov
    uses: codecov/codecov-action@v1
    with:
        token: ${{ secrets.CODECOV_TOKEN }}

        - name: Scala 2.13 build
        if: startsWith(matrix.scala, '2.13')
        run: sbt ++${{ matrix.scala }} coverage test coverageReport
      - name: Scala build
        if: '!startsWith(matrix.scala, ''2.13'')'
        run: sbt ++${{ matrix.scala }} test
      - name: Publish to Codecov.io
        if: startsWith(matrix.scala, '2.13')
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true